apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: finalproject-argo-application
  namespace: argocd
spec:
  project: default
  source:
    repoUrl: https://github.com/ogonommo/finalproject.git
    targetRevision: HEAD
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: finalproject
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true